## Author:Eric 2017.09.20
## Customize the test machine

version: 2

jobs:
  php71:
    docker:
      - image: circleci/php:7.1.8-browsers
      environment:
        TZ: "/usr/share/zoneinfo/Asia/Taipei"
    working_directory: ~/laravel
    steps:
      - checkout
      - run: composer self-update
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor
      - run: ./vendor/bin/phpunit
